---
- name: disable temporary challenge sites
  import_tasks: disable_challenge_sites.yml

- name: restart memcached
  service:
    name: memcached
    state: restarted
    use: service

- name: reload php-fpm
  service:
    name: php{{ php_version }}-fpm
    state: reloaded
    use: service

- name: restart journald
  service:
    name: systemd-journald
    state: restarted
#    use: service

- import_tasks: reload_nginx.yml

- name: restart mysql server
  service:
    name: mariadb
    state: restarted
    enabled: true
    use: service
