# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: productionpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: web
    salt: "generateme"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`radicle.local.host`) must match up with the site name in the above file.
vault_wordpress_sites:
  radicle.local.host:
    admin_password: admin
    env:
      db_password: password
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "5^XmjxOvYOCwO<Ku$VDg2(mtY}sMgtKHL!L1Bv`7]jb_4XpAiIoZt%2/4GR.iv&W"
      secure_auth_key: "q.lYx:XRVY4ke5CK6sWDqTK#$Uke-[.eaHzYaEV<8[}O,}kpnu^,xgE-Y.799]yS"
      logged_in_key: "@=]?IJBk2_a4U=(M9jd2a&lLA4&-$yT.X6@XXY](wT/MNc%PgkI<8Tn/$pNnOM!`"
      nonce_key: "0bp-bB+c6gW6QJCTi<.ut*808i&ohfjtutk{DLVGqP+E94wxN$.lJ+Z6V0qxjqFx"
      auth_salt: "N>Zr9SI}L=waO$$9J/7n.{]-(M:[{KPlNO<C]DR=@Uq/4w$7q)$sWN*bFV/_`</w"
      secure_auth_salt: "m{O{@&b_4aM+!K1E]M|><;YvA>EwrOn?>RGSMv]a/ldaX7%%n};u}f=%6^Ri[l6L"
      logged_in_salt: "1x%R;a-ERCQK!T5K`,Z5WX-^6GKH#Gp6u;mBnX#q)Evl}(;Hk{Z>..}9;!uq[Bua"
      nonce_salt: "b/%jxnOJR:lW=7i&M);z!zCjYG,S9*-eV>w0qqp}S[EV|Pd2;J!)i)uLp%*c,G!h"
