# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  radicle.local.host:
    site_hosts:
      - canonical: radicle.local.host
        # redirects:
        #   - www.radicle.local.host
    local_path: ..
    public_path: public
    upload_path: content/uploads
    repo: git@github.com:janusz-stryve/radicle.git # replace with your Git repo URL
    branch: main
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
    xmlrpc:
      enabled: false
