# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  radicle.yumistudio.pl:
    site_hosts:
      - canonical: staging.radicle.yumistudio.pl
        # redirects:
        #   - otherdomain.com
    local_path: ..
    public_path: public
    upload_path: content/uploads
    repo: git@github.com:example/radicle.yumistudio.pl.git # replace with your Git repo URL
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
    xmlrpc:
      enabled: false
